# Uncomment this line to define a global platform for your project
# platform :ios, '8.4'

target 'backlogForiOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  # Pods for backlogForiOS

  target 'backlogForiOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
  end

  target 'backlogForiOSUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
  end

end
